apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - name: http
      port: {{ .Values.service.ports.httpPort }}
      protocol: {{ .Values.service.ports.httpProtocol }}
      targetPort: {{ .Values.service.ports.httpTargetPort }}
    - name: rcp
      port: {{ .Values.service.ports.rcpPort }}
      protocol: {{ .Values.service.ports.rcpProtocol }}
      targetPort: {{ .Values.service.ports.rcpTargetPort }}
    - name: seflan-tcp
      port: {{ .Values.service.ports.serflanTcpPort }}
      protocol: {{ .Values.service.ports.serflanTcpProtocol }}
      targetPort: {{ .Values.service.ports.serflanTcpTargetPort }}
    - name: serflan-udp
      port: {{ .Values.service.ports.serflanUdpPort }}
      protocol: {{ .Values.service.ports.serflanUdpProtocol }}
      targetPort: {{ .Values.service.ports.serflanUdpTargetPort }}
    - name: serfwan-tcp
      port: {{ .Values.service.ports.serfwanTcpPort }}
      protocol: {{ .Values.service.ports.serfwanTcpPortcpProtocol }}
      targetPort: {{ .Values.service.ports.serfwanTcpTargetPort }}
    - name: serfwan-udp
      port: {{ .Values.service.ports.serfwanUdpPort }}
      protocol: {{ .Values.service.ports.serfwanUdpProtocol }}
      targetPort: {{ .Values.service.ports.serfwanUdpTargetPort }}
    - name: server
      port: {{ .Values.service.ports.serverPort }}
      protocol: {{ .Values.service.ports.serverProtocol }}
      targetPort: {{ .Values.service.ports.serverTargetPort }}
    - name: consuldns
      port: {{ .Values.service.ports.consuldnsPort }}
      protocol: {{ .Values.service.ports.consuldnsProtocol }}
      targetPort: {{ .Values.service.ports.consuldnsTargetPort }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
