{{- if .Values.ingress.argo }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acyl-argo
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: {{ .Values.namespace }}
  annotations:
      kubernetes.io/ingress.class: argo-tunnel
spec:
  rules:
    {{- if .Values.is_dqa }}
    - host: {{ .Values.env_name }}-{{ .Values.ingress.argo_host }}
    {{- else }}
    - host: {{ .Values.ingress.argo_host }}
    {{- end }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.service.name }}
              servicePort: {{ .Values.service.internalPort }}
{{- end }}
