replicaCount: 1
image:
  repository: consul
  tag: 0.8.4
  imagePullPolicy: Always
  pullSecrets: quay-key

app:
  env: qa
  envMetadata: false

ingress:
  enabled: false
  hosts:
  annotations:

service:
  name: consul
  type: ClusterIP
  sessionAffinity: None
  ports:
    httpPort: 8500
    httpProtocol: TCP
    httpTargetPort: 8500
    rcpPort: 8400
    rcpProtocol: TCP
    rcpTargetPort: 8400
    serflanTcpPort: 8301
    serflanTcpProtocol: TCP
    serflanTcpTargetPort: 8301
    serflanUdpPort: 8301
    serflanUdpProtocol: UDP
    serflanUdpTargetPort: 8301
    serfwanTcpPort: 8302
    serfwanTcpProtocol: TCP
    serfwanTcpTargetPort: 8302
    serfwanUdpPort: 8302
    serfwanUdpProtocol: UDP
    serfwanUdpTargetPort: 8302
    serverPort: 8300
    serverProtocol: TCP
    serverTargetPort: 8300
    consuldnsPort: 8600
    consuldnsProtocol: TCP
    consuldnsTargetPort: 8600

resources: {}
